name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - run: |
        ls -l
        cd alpine
        docker build . --file Dockerfile --tag my-alpine:3.21
        docker run --name myalpine -dt --entrypoint "/bin/sh" my-alpine:3.21
        docker export --output=myalpine.tar myalpine
        gzip myalpine.tar
        gh release create v0.0.1 myalpine.tar.gz
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
