name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-alpine:3.21
    # - uses: addnab/docker-run-action@v3
    #   with:
    #     image: alpine:3.21
    #     run: echo "hello world"
    - run: |
        docker run --name myalpine -dt --entrypoint "/bin/sh" alpine:3.21
        docker export --output=myalpine.tar myalpine
        ls -l
        gh release create v0.0.1 myalpine.tar
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
